<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaketSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                "id_jenis" => 1,
                "nama" => "SS 1",
                "harga" => 50000,
                "speed" => 1.6,
                "aktif" => 30,
                "keterangan" => "Masa aktif 30 hari dengan kuota 50 GB",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id_jenis" => 1,
                "nama" => "SS 2",
                "harga" => 100000,
                "speed" => 1.6,
                "aktif" => 30,
                "keterangan" => "Masa aktif 30 hari dengan kuota 100 GB",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id_jenis" => 2,
                "nama" => "Wireless 3 Jam",
                "harga" => 2000,
                "speed" => 2.5,
                "aktif" => 1,
                "keterangan" => "Masa aktif 1 hari dengan kuota 3 jam",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id_jenis" => 2,
                "nama" => "Wireless 10 Jam",
                "harga" => 5000,
                "speed" => 2.5,
                "aktif" => 1,
                "keterangan" => "Masa aktif 1 hari dengan kuota 10 jam",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id_jenis" => 2,
                "nama" => "Wireless 24 Jam",
                "harga" => 10000,
                "speed" => 2.5,
                "aktif" => 1,
                "keterangan" => "Masa aktif 1 hari dengan kuota 24 jam",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id_jenis" => 2,
                "nama" => "Optik 3 Jam",
                "harga" => 2000,
                "speed" => 5,
                "aktif" => 1,
                "keterangan" => "Masa aktif 1 hari dengan kuota 3 jam",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id_jenis" => 2,
                "nama" => "Optik 8 Jam",
                "harga" => 5000,
                "speed" => 5,
                "aktif" => 1,
                "keterangan" => "Masa aktif 1 hari dengan kuota 8 jam",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id_jenis" => 2,
                "nama" => "Optik 15 Jam",
                "harga" => 10000,
                "speed" => 5,
                "aktif" => 1,
                "keterangan" => "Masa aktif 1 hari dengan kuota 15 jam",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id_jenis" => 2,
                "nama" => "Optik 24 Jam",
                "harga" => 2000,
                "speed" => 5,
                "aktif" => 1,
                "keterangan" => "Masa aktif 1 hari dengan kuota 24 jam",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id_jenis" => 3,
                "nama" => "KUOTA 5K",
                "harga" => 5000,
                "speed" => 2.5,
                "aktif" => 5,
                "keterangan" => "Masa aktif 5 hari dengan kuota 5 GB",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id_jenis" => 3,
                "nama" => "KUOTA 10K",
                "harga" => 10000,
                "speed" => 2.5,
                "aktif" => 10,
                "keterangan" => "Masa aktif 10 hari dengan kuota 10 GB",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id_jenis" => 3,
                "nama" => "KUOTA 20K",
                "harga" => 20000,
                "speed" => 2.5,
                "aktif" => 15,
                "keterangan" => "Masa aktif 15 hari dengan kuota 20 GB",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id_jenis" => 3,
                "nama" => "KUOTA 30K",
                "harga" => 30000,
                "speed" => 2.5,
                "aktif" => 20,
                "keterangan" => "Masa aktif 20 hari dengan kuota 30 GB",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id_jenis" => 3,
                "nama" => "KUOTA 4K",
                "harga" => 40000,
                "speed" => 2.5,
                "aktif" => 30,
                "keterangan" => "Masa aktif 30 hari dengan kuota 40 GB",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id_jenis" => 3,
                "nama" => "KUOTA FO 5K",
                "harga" => 5000,
                "speed" => 4,
                "aktif" => 7,
                "keterangan" => "Masa aktif 7 hari dengan kuota 10 GB",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id_jenis" => 3,
                "nama" => "KUOTA FO 10K",
                "harga" => 10000,
                "speed" => 4,
                "aktif" => 14,
                "keterangan" => "Masa aktif 14 hari dengan kuota 20 GB",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id_jenis" => 3,
                "nama" => "KUOTA FO 20K",
                "harga" => 20000,
                "speed" => 4,
                "aktif" => 21,
                "keterangan" => "Masa aktif 21 hari dengan kuota 50 GB",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id_jenis" => 4,
                "nama" => "HEMAT 1",
                "harga" => 60000,
                "speed" => 1.6,
                "aktif" => 30,
                "keterangan" => "Masa aktif 30 hari dengan kuota tanpa FUB berlaku untuk 1 device",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id_jenis" => 4,
                "nama" => "HEMAT 2",
                "harga" => 100000,
                "speed" => 2.5,
                "aktif" => 30,
                "keterangan" => "Masa aktif 30 hari dengan kuota tanpa FUB berlaku untuk 1 device",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id_jenis" => 4,
                "nama" => "OK 1",
                "harga" => 30000,
                "speed" => 1.2,
                "aktif" => 30,
                "keterangan" => "Masa aktif 30 hari dengan kuota tanpa FUB berlaku untuk 1 device",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id_jenis" => 4,
                "nama" => "OK 2",
                "harga" => 60000,
                "speed" => 3,
                "aktif" => 30,
                "keterangan" => "Masa aktif 30 hari dengan kuota tanpa FUB berlaku untuk 1 device",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "id_jenis" => 4,
                "nama" => "OK 3",
                "harga" => 100000,
                "speed" => 1.2,
                "aktif" => 30,
                "keterangan" => "Masa aktif 30 hari dengan kuota tanpa FUB berlaku untuk 1 device",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
        ];

        DB::table('paket')->insert($data);
    }
}
